### PR TITLE
Convert settings format to TOML and a ton of regex changes

### PR DESCRIPTION
**Pull request by evildarkarchon**
Got restless, so I converted the configuration format from configparser INI to TOML using tomlkit.

tomlkit is less restrictive than configparser, it represents values in their proper form, bools as bools, ints as ints, etc.

No more having to convert every value to a string, no more special function to convert a string to a bool and no more weird string matching tricks to determine if a value is true or false.

### CODE REVIEW

**Comment by evildarkarchon** [comment]
Since I had more time, I decided to do Part 2 of my regex work. I was looking for a better way to get the crash_error and crash_ver values (hardcoded slicing was not always reliable) and things just kinda spiraled out from there. I already know it is a bit slower at large scale, but not nearly as bad as my initial attempts. Current code has 14-16 second runtime for around 400 logs, previous attempts had runtime in the minutes.

**Comment by evildarkarchon** [comment]
Don't know what I did, but runtimes seem to have gone down to the same as before my changes (5-8 second runtime).

**Comment by evildarkarchon** [comment]
BTW, this duplicate results from check_plugins() bug was there before I started my regex work. The solution to the problem was kind of an epiphany to tell the truth.

**Comment by evildarkarchon** [comment]
Didn't expect to use re's IGNORECASE flag, but some of the logs I saw today showed that, as I had it, there was the possibility of false-negatives for detecting whether people had things like UFO4P installed if the file name wasn't in the exact same case as it is in the download file. Why someone would have the file name in a different case, I could only speculate, but someone did it.

**Comment by evildarkarchon** [comment]
This project is about as done as any coding project can claim to be. I'll be field testing it more, but current tests look good. It should be merge-ready now.

**Comment by evildarkarchon** [comment]
I moved the UI setup logic to the __init__ method because what the setup_ui function was doing could just as easily be done with __init__ and adding a positional argument for the parent window. I've tested it out with both CLAS and PACT and have noticed no difference. This also has the pleasant side-effect of shutting VSCode up about a bunch of methods not being available in None, because outside setup_ui() the type checker only sees those objects as None.

**Comment by evildarkarchon** [comment]
Scratch the previous completion statement. Now, unless I get restless again, it should be done. This is the version I will be using to scan people's logs on discord until the main branch gets updated.

**Comment by evildarkarchon** [comment]
I will return to the project of reducing our false-positivity rate through regex another day, this will (probably) be my last commit to this branch.

**Comment by evildarkarchon** [comment]
Couldn't leave a job half-done. I found the mistake that was making my patterns not match, so I applied that and results are good so far. These regex patterns make sure that the match starts at the beginning of a "word" and that the end of the pattern should also correspond with the end of the string, reducing the chances that plugins that coincidentally have the name of one of the plugins in the database to almost nil.
I also removed a bunch of wildcard matches by researching their actual plugin names and changing the patterns to match based on that. If a mod comes in multiple different plugin formats, the pattern was adjusted to allow for that.
I also combined the Scrap Everything entries since they (like gender specific skeletons) had essentially identical error messages.

**Comment by evildarkarchon** [comment]
The regex library I decided to use is just a simple pip install away, `pip install regex`

**Comment by evildarkarchon** [comment]
I'm hoping that this really is the final draft of this project.

**Comment by evildarkarchon** [comment]
I attempted to try and write some code to convert an existing INI file to the toml format but so far haven't had any luck because the spaces in the keys tomlkit freak out. So far no luck doing an in-place substitution.

**Comment by evildarkarchon** [comment]
First attempt at sanitization was a bust, will refine later. Did manage to implement ini import functionality, though. Also, the commit with the code doesn't indicate that the code is there because I forgot to commit the initial code before fixing it.

**Comment by evildarkarchon** [comment]
Second attempt was also a bust, gonna wait until after release before taking another tackle at it.

**Comment by GuidanceOfGrace** [comment]
No more pull requests till June 1st pls.

**Pull request merged**
