### PR TITLE
PySide GUI Conversion

### PR DESCRIPTION
**Pull request by evildarkarchon**
Here's the PyQt6 code if you want it. That PyQt6 vs. pyinstaller comment was "Challenge accepted" for me. Hopefully you have as much luck with it as I did.

### CODE REVIEW

**Comment by evildarkarchon** [comment]
I'm using pyinstaller v5.7.0, it has hook plugins for pyqt6, so if you're using an older version, maybe that's the answer. It works with Python 3.9+. Other than that, I'm scratching my head about it as much as you are, maybe more since I can't replicate the issue.

**Comment by evildarkarchon** [comment]
Experiment proposal: Using PySide6 instead of PyQt6, PySide does generate slightly bigger binaries, but if you can get pyinstaller to cooperate with it, it might be viable. From what I've seen, the differences when it comes to the API are subtle, but it runs the code in this PR as-is. Again, for me, pyinstaller worked just fine with PySide, hopefully it works for you if you decide to go with it.

**Comment by GuidanceOfGrace** [comment]
I'll be delaying this commit a while longer just so I can test a few things.
Currently not implemented in v6.25, but next version probably will.

**Comment by evildarkarchon** [comment]
To be honest, this PR was mainly an RFC, so this is good news to me 😁.

**Comment by evildarkarchon** [comment]
Bringing this up to current main to make merging easier. Going to make sure this is current until it's either merged or closed. I like writing python too much to stay idle on this. 🙂

**Pull request merged**
